spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
  redis:
    host: 192.168.6.122
    port: 6379
    password:
    timeout: 360s # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 600s # 连接池最大阻塞等待时间（使用负值表示没有限制）
logicserver:
  name: yingsanzhang
  connector: hall
jwt:
  secret: MYWUWU1234a
  expiration: 120000